# Generated by Django 4.0.5 on 2022-06-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0013_actors_movie_actors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Actors',
            new_name='Actor',
        ),
    ]
